language: node_js
node_js:
  - "lts/erbium"
before_script:
  - export TZ=America/New_York
install:
    - npm ci --prefix client
    - npm ci --prefix server
cache:
  directories:
    - $HOME/.npm
    - client/node_modules
    - server/node_modules
script:
  - npm test --prefix client
  - npm run lint --prefix client
  - npm test --prefix server
  - npm run lint --prefix server
  - npm run build --prefix client
